version: 2.1

commands: 
  install:
    steps:
      - run: pip install . --user
      - run: pip install -r requirements.txt --user

jobs:
    build:
      docker:
        - image: circleci/python:3.6  # primary container for the build job
      steps:
        - checkout
        - install
        - run: make test
    lint:
      docker:
        - image: circleci/python:3.6  # primary container for the build job
      steps:
        - checkout
        - install
        - run: make lint
    python35:
      docker:
        - image: circleci/python:3.7
      steps:
        - checkout
        - install
        - run: make test
    python37:
      docker:
        - image: circleci/python:3.8.0b2-buster
          auth:
            username: jmancuso9  # can specify string literal values
            password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - install
        - run: make test
    python38:
      docker:
        - image: circleci/python:3.8
      steps:
        - checkout
        - run: make
        - run: make test
    CodeCoverage:
      docker:
        - image: circleci/python:3.6
      steps:
        - checkout
        - install
        - run: pip install -r requirements.txt --user
        - run: make coverage
        - run: make deepsource

orbs:
    masonite: masonite/trigger@1.0.0

workflows: 
  version: 2
  build_and_test:
    jobs: 
      - build: # Python 3.6
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - lint: # Python 3.6
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python35:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python37:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - python38:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - CodeCoverage:
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - masonite/trigger:
          name: MasoniteValidation
          repo: masoniteframework/validation
          branch: 3.0
          environment: MASONITE_DEPENDENT_BRANCH=${CIRCLE_BRANCH:-2.2}
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - masonite/trigger:
          name: MasoniteAPI
          repo: masoniteframework/api
          branch: "2.2"
          environment: BUILD_BRANCH=${CIRCLE_BRANCH:-2.2}
          requires:
              - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^.*/
      - masonite/deploy:
          username: josephmancuso
          password: $PYPI_PASSWORD
          requires:
            - MasoniteValidation
            - MasoniteAPI
            - CodeCoverage
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
